### ISSUE TITLE
Redmine 404 error

### ISSUE THREAD

**Issue by MotherLoveBone** [danielanguita/Redmine-Inventory-Manager#18]
Hola Daniel,
Primero de todo felicitarte por la iniciativa de este plugin, utilizo Redmine intensivamente desde hace ya dos años y echaba en falta un add-on de estas carácteristicas.
El problema, tengo instalada la versión 3.0.3 de Redmine, y tras instalar el plugin como indicas y reiniciar los servicios aparece el menú "Inventory" en la parte superior de la interfaz pero al pulsar sobre el enlace me envia a la típica página de error 404 "the page you were trying to access doesn't exist or has been removed"

Entiendo que el plugin está bien instalado pues aparece en /Administración/Extensiones aparece como tal; por otra parte, he revisado el production.log y me aparecen estos errores:

- "Started GET "/redmine/inventory/top" for 127.0.0.1 at 2015-07-03 13:12:53 +0200
AbstractController::ActionNotFound (The action 'top' could not be found for InventoryController):"

- "Started GET "/redmine/inventory/index.html" for 127.0.0.1 at 2015-07-03 13:12:45 +0200
Processing by InventoryController#index as HTML
  Current user: jmontes (id=1)
Completed 404 Not Found in 5ms (ActiveRecord: 1.0ms)
ActiveRecord::RecordNotFound (Couldn't find all InventoryWarehouses with 'id': (all, {:order=>"name"}) (found 0 results, but was looking for 2)):"

No se si podrías traer un poco de luz a mi problema.
Muchas gracias de antemano por tu ayuda y tu atención

**Comment by w0www** [comment]
Muy buenas tardes. Nose si estamos hablando de lo mismo pero me pasaba algo similar. El problema esta en como se hacen las rutas en este plugin y pueden que se solapen con otras de otros plugins. Para descartar esto intenta probarlo solamente redmine con este plugin y todos tl%
