### ISSUE TITLE
Update to support 3.1.0 ?

### ISSUE THREAD

**Issue by mbrownnycnyc** [danielanguita/Redmine-Inventory-Manager#20]
Hello Dan,

Thanks for taking time to author this plugin.

It appears to not be compatible with Redmine 3.1.0.  Are you considering support for it?

Thanks,

Matt

**Comment by w0www** [comment]
I think not. This plugin is deprecated because we dont have time to improvements. If you want, you could done a fork and propose a new version. We try help you.

**Comment by u2mike** [comment]
hi dan
any change that you maybe enhance this nice plugin in near future?
thanks
mike

**Comment by fastuser** [comment]
With a couple of changes, we would be willing to pay for this to be updated.
Interested ?

**Comment by danielanguita** [comment]
Sure, what would be your requirement?

**Comment by w0www** [comment]
Any news about this? I am going to update this plugin to new versions ;)

**Comment by fastuser** [comment]
Hi,
No sorry, Im not sure if we need this yet.
Thanks for catching up though!

**Comment by w0www** [comment]
Ok dont worry. I need this to my project. I going to update and do some improvements! Thanks ;)

**Comment by w0www** [comment]
@fastuser i close this issue. The plugin is updated!
